### ISSUE TITLE
Some bugs found

### ISSUE THREAD

**Issue by JoaoGabrielCorrea** [SmartCash/android#1]
Sometimes a black screen appears in transition from login to registration.

Receipt symbol has to be down.

In the receive tab you enter the value and change the QR code.
The higher the value, the higher the points in the qr code.

After erasing the values ​​the amount in usd remains as 1 smart.

After changing currency conversion need to exit the wallet to upgrade.

After the new installation and registration of the pin the wallet lock

After the new pin installation and registration, the wallet locks and returns after a few moments

**Comment by enriquesouza** [comment]
@JoaoGabrielCorrea I fixed the registration errors. Please use https://github.com/SmartCash/android/releases/tag/v0.1.1-alpha

**Comment by enriquesouza** [comment]
After erasing the values ​​the amount in USD remains as 1 smart. - OK
Sometimes a black screen appears in the transition from login to registration. - OK
In the receive tab, you enter the value and change the QR code. - OK (That is normal)
The higher the value, the higher the points in the QR code. - OK (That is normal)
After changing currency conversion need to exit the wallet to upgrade. - OK
After the new installation and registration of the pin the wallet lock - OK
After the new pin installation and registration, the wallet locks and returns after a few moments - OK
