### ISSUE TITLE
Continue without pin dialog message, confusing...

### ISSUE THREAD

**Issue by hockleyj** [SmartCash/android#3]
on login when you click to continue without pin.   you are presented with a dialog
"Are you sure you want to proceed without PIN ? You wont be able to use it off-line"

the second part of this message "You wont be able to use it off-line"  appears ambiguous.

It infers that  without a pin you cannot use it offline?  which leaves the user asking the question why?   if  the pin has no link to usage offline then this should be reworded.  if having a pin does allow offline usage, then it should be reworded  to something like "for offline use a pin is required etc"

**Comment by enriquesouza** [comment]
If you continue without PIN then I don't save the password and don't encrypt that. It is more secure.
