### ISSUE TITLE
global currency setting not persistent between logins

### ISSUE THREAD

**Issue by hockleyj** [SmartCash/android#4]
logged in then changed global currency from USD to SMART. logged out then logged in  setting was back to USD instead of  SMART.

**Comment by hockleyj** [comment]
the above is where you  log out before exiting the app.
if you just  exit the app then   re open.  the setting persists.   note that due to the loggout icon being at the top,  it could lead to many people  click to loggout before exiting the app  from a workflow perspective.

**Comment by enriquesouza** [comment]
If you log out we delete all of your preferences. So it is normal behavior.
