### ISSUE TITLE
send screen contacts blank no labels for spend or rewards 1

### ISSUE THREAD

**Issue by hockleyj** [SmartCash/android#5]
on the send screen when you click on contacts.  it shows a  3 wallets but  no icon or text for  spend or rewards 1 .  only rewards 2 has label text  this only appeared on the Sony experia Z  but not the Samsung galaxy s9+   might be due to text sizing or padding between label and select button ?

**Comment by enriquesouza** [comment]
Not sure yet. I need to check if this is compatible over all devices

**Comment by enriquesouza** [comment]
Fixed and will be published on v0.1.2
